Dockerfile: use cargo install --locked instead of --frozen
--frozen produces:
Step 4/9 : RUN RUSTFLAGS="-C target-cpu=skylake" cargo install --frozen --path . --root /install
 ---> Running in 47ce2f1eb9e0
  Installing locations-rs v0.1.0 (/)
error: failed to get `actix-rt` as a dependency of package `locations-rs v0.1.0 (/)`

Caused by:
  attempting to make an HTTP request, but --frozen was specified

(I've apparently didn't understand well what it means)